# Generated by Django 4.2.6 on 2023-10-19 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_first_name_remove_user_last_name_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('teacher_id', models.PositiveIntegerField()),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True)),
                ('phone_number', models.TextField()),
                ('join_date', models.DateTimeField()),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5)),
                ('address', models.TextField(blank=True)),
                ('religion', models.CharField(blank=True, choices=[('Islam', 'Islam'), ('Hindu', 'Hindu'), ('Chirstian', 'Chirstian'), ('Buddist', 'Buddist'), ('Others', 'Others')], max_length=10)),
                ('teacher_image', models.ImageField(blank=True, upload_to='teacher/img/')),
                ('job_experience', models.PositiveIntegerField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('account.user',),
        ),
        migrations.RenameField(
            model_name='student',
            old_name='teacher_id',
            new_name='admision_id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='job_experience',
            new_name='roll_no',
        ),
        migrations.RemoveField(
            model_name='student',
            name='join_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='teacher_image',
        ),
        migrations.AddField(
            model_name='student',
            name='student_image',
            field=models.ImageField(blank=True, upload_to='student/img/'),
        ),
    ]
