# Generated by Django 4.2.6 on 2023-10-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_student_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admision_id',
            field=models.PositiveIntegerField(auto_created=1000),
        ),
    ]
