# Generated by Django 4.2.6 on 2023-10-24 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_student_tuition_fees_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='admision_id',
        ),
    ]
