# Generated by Django 4.2.6 on 2023-11-06 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_staff_teacher_department_alter_student_blood_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='department',
        ),
    ]
