# Generated by Django 4.2.6 on 2023-11-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_remove_staff_staff_id_remove_teacher_teacher_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_designation',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
