# Generated by Django 4.2.7 on 2023-12-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_remove_staff_first_name_remove_staff_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='otp_token',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
