# Generated by Django 4.2.7 on 2023-12-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_student_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_image',
            field=models.ImageField(blank=True, default='student_avatar.png/', upload_to='student/img/'),
        ),
    ]
