# Generated by Django 4.2.6 on 2023-10-21 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_teacher_rename_teacher_id_student_admision_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_1st', models.BooleanField(default=False)),
                ('is_complete_1st', models.BooleanField(default=False)),
                ('semester_2nd', models.BooleanField(default=False)),
                ('is_complete_2nd', models.BooleanField(default=False)),
                ('semester_3rd', models.BooleanField(default=False)),
                ('is_complete_3rd', models.BooleanField(default=False)),
                ('semester_4th', models.BooleanField(default=False)),
                ('is_complete_4th', models.BooleanField(default=False)),
                ('semester_5th', models.BooleanField(default=False)),
                ('is_complete_5th', models.BooleanField(default=False)),
                ('semester_6th', models.BooleanField(default=False)),
                ('is_complete_6th', models.BooleanField(default=False)),
                ('semester_7th', models.BooleanField(default=False)),
                ('is_complete_7th', models.BooleanField(default=False)),
                ('semester_8th', models.BooleanField(default=False)),
                ('is_complete_8th', models.BooleanField(default=False)),
                ('students', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.student')),
            ],
        ),
        migrations.CreateModel(
            name='installment_4th',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='installment_4th', max_length=30)),
                ('pay', models.PositiveIntegerField()),
                ('is_paid', models.BooleanField(default=False)),
                ('semesters', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installment_4th', to='student.semester')),
            ],
        ),
        migrations.CreateModel(
            name='installment_3rd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='installment_3rd', max_length=30)),
                ('pay', models.PositiveIntegerField()),
                ('is_paid', models.BooleanField(default=False)),
                ('semesters', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installment_3rd', to='student.semester')),
            ],
        ),
        migrations.CreateModel(
            name='installment_2nd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='installment_2nd', max_length=30)),
                ('pay', models.PositiveIntegerField()),
                ('is_paid', models.BooleanField(default=False)),
                ('semesters', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installment_2nd', to='student.semester')),
            ],
        ),
        migrations.CreateModel(
            name='installment_1st',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='installment_1st', max_length=30)),
                ('pay', models.PositiveIntegerField()),
                ('is_paid', models.BooleanField(default=False)),
                ('semesters', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installment_1st', to='student.semester')),
            ],
        ),
    ]
