# Generated by Django 4.2.6 on 2023-10-24 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_student_semester'),
        ('student', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('1st Installment', '1st Installment'), ('2nd Installment', '2nd Installment'), ('3rd Installment', '3rd Installment'), ('4th Installment', '4th Installment')], max_length=50)),
                ('amount', models.PositiveIntegerField(default=3750)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Semesters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('1st Semester', '1st Semester'), ('2nd Semester', '2nd Semester'), ('3rd Semester', '3rd Semester'), ('4th Semester', '4th Semester'), ('5th Semester', '5th Semester'), ('6th Semester', '6th Semester'), ('7th Semester', '7th Semester'), ('8th Semester', '8th Semester')], max_length=50)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('Student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.student')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.DeleteModel(
            name='first_installment',
        ),
        migrations.AddField(
            model_name='installments',
            name='semester',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.semesters'),
        ),
    ]
