# Generated by Django 4.2.6 on 2023-10-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_installments_semesters_delete_first_installment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installments',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
