# Generated by Django 4.2.6 on 2023-10-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_alter_installments_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='installments',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Bkash', 'Bkash'), ('Others', 'Others')], max_length=15),
        ),
    ]
