# Generated by Django 4.2.6 on 2023-11-04 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_invoice_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_list',
            name='installment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='student.installments'),
        ),
        migrations.AddField(
            model_name='invoice_list',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='student.semesters'),
        ),
    ]
