# Generated by Django 4.2.6 on 2023-11-04 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_student_admision_id'),
        ('student', '0013_invoice_list_installment_invoice_list_semester'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invoice_List',
            new_name='Invoice',
        ),
    ]
