# Generated by Django 4.2.6 on 2023-11-05 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_student_admision_id'),
        ('student', '0014_rename_invoice_list_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration_fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Registrations Fees', max_length=50)),
                ('amount', models.CharField(choices=[('1st Semester', 1600), ('2nd Semester', 1600), ('3rd Semester', 1600), ('4th Semester', 1800), ('5th Semester', 1800), ('6th Semester', 1900), ('7th Semester', 1900), ('8th Semester', 1700)], max_length=20)),
                ('pay_date', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_method', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Bkash', 'Bkash'), ('Others', 'Others')], max_length=15)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.student')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.semesters')),
            ],
        ),
    ]
