# Generated by Django 4.2.6 on 2023-11-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_alter_registration_fees_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration_fees',
            name='pay_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
