# Generated by Django 4.2.6 on 2023-11-05 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_alter_registration_fees_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration_fees',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Registration_fees_semester', to='student.semesters'),
        ),
    ]
