# Generated by Django 4.2.7 on 2023-12-16 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_alter_registration_fees_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='registration_fees',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='student.registration_fees'),
        ),
    ]
