# Generated by Django 4.2.6 on 2023-10-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('department_code', models.PositiveIntegerField()),
                ('established_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
