# Generated by Django 4.2.6 on 2023-10-21 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_first_installment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='first_installment',
        ),
    ]
