# Generated by Django 4.2.6 on 2023-10-24 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_delete_first_installment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
