# Generated by Django 4.2.6 on 2023-11-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0005_delete_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('department_code', models.PositiveIntegerField()),
                ('established_date', models.DateTimeField(auto_now_add=True)),
                ('HOD', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
